stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the Docker image..."

test-job:
  stage: test
  script:
    - echo "Running tests..."

deploy-job:
    stage: deploy
    script:
        - echo "Deploying the application..."