apiVersion: v1
kind: Service
metadata:
  name: service-sepa-credit-transfer-api-service
  labels:
    app: service-sepa-credit-transfer-api
spec:
  selector:
    app: service-sepa-credit-transfer-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}