spring:
  application:
    name: dkb
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
processor:
  name: mfa-processor
  enabled: true
  scheduled:
    fixedDelay: 100
    initialDelay: 100

