spring:
  application:
    name: dkb
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
processor:
  mfa_authorized:
    enabled: true
    fixedRate: PT5S
    fixedDelay: PT5S
  name: mfa-processor
  enabled: true
  scheduled:
    fixedDelay: 100
    initialDelay: 100