package com.bgpark.demo.dkb.faud.payment.service.model

data class DeviceData(
    var app: String? = null,
    var os: String? = null,
    var version: String? = null,
    var appId: String? = null,
    var systemModel: String? = null,
    var systemVersion: String? = null,
    var currencySet: String? = null,
    var countrySet: String? = null,
    var languageSet: String? = null,
    var timezoneSet: String? = null,
    var bsaSid: String? = null,
    var bsaDid: String? = null,
    var bsaVersion: String? = null,
    var proxyHost: String? = null,
    var proxyPort: String? = null,
    var gyroscopeX: String? = null,
    var gyroscopeY: String? = null,
    var gyroscopeZ: String? = null,
    var locationLat: String? = null,
    var locationLong: String? = null,
    var locationAlt: String? = null,
    var locationAccur: Int? = null,
    var carrierNetcode: String? = null,
    var carrierNetcountry: String? = null,
    var carrierNetname: String? = null,
    var carrierAllowVoip: String? = null,
    var carrierIccid: String? = null,
    var carrierImsi: String? = null,
    var carrierImei: String? = null,
    var wifiCurSsid: String? = null,
    var wifiCurBssid: String? = null,
    var wifiKnown: String? = null,
    var wifiNeighbors: String? = null,
    var siRooted: String? = null,
    var siRootmgmt: String? = null,
    var siDangerApps: String? = null,
    var siRootCloak: String? = null,
    var siTestkeys: String? = null,
    var siDangerProps: String? = null,
    var siWritableSystem: String? = null,
    var siDangerBins: String? = null,
//    var servernonce: ServerNonce? = null,
//    var localIpAddress: String? = null,
//    var remoteIpAddress: String? = null,
//    var userIds: String? = null,
//    var appsSms: String? = null,
//    var appsPush: String? = null,
//    var appsOverlay: String? = null,
//    var appsAccessService: String? = null,
//    var appsSafetyNetharmful: String? = null,
//    var appsCategory: String? = null,
//    var serialnumber: String? = null,
//    var safetyNetresult: SafetyNetResult? = null,
//    var playIntegrityResult: PlayIntegrityResult? = null,
//    var enrollmentAt: String? = null,
//    var portfolio: Portfolio? = null,
//    var preferredDevice: Boolean? = null, // not saved in db
//    var alias: String? = null, // not saved in db
//    // see workaround in ValidationResultParsingService, mapping here ViyaPlayIntegrityResult,
//    // not saved in the database and send to viya at runtime
//    // if all viya retry fails, then it's not send in retry with scheduled job
//    var viyaPlayIntegrityResult: ViyaPlayIntegrityResult? = null,
//    var viyaValidationResult: ValidationResults? = null,
)